### ISSUE TITLE
Documentation - Translate to Spanish

### ISSUE THREAD

**Issue by castarco** [kindspells/astro-shield#123]
Translate the documentation site to Spanish

**Comment by JollyJolli** [comment]
Hey there! I would love to help with this

**Comment by Samyak-Waghmare** [comment]
Hey, Can you assign me this issue?

**Comment by castarco** [comment]
Hi @Samyak-Waghmare , I prefer not to assign issues. Announcing it here is enough.

On the other hand, and please don't take this the wrong way, I'd prefer this translation to be made by a native Spanish speaker, like me, rather by someone who at most has it as second language or depends on automatic translation tools.

**Comment by pmj-chosim** [comment]
Hello. I want to translate it in Korean. If you don't mind, could I do it?

**Comment by castarco** [comment]
Hi @pmj-chosim , sure, feel free to create a new issue for it 😃 , I think I didn't create one for that. I'll take care of adding the proper labels.

**Comment by pmj-chosim** [comment]
Yes. I make an issue and on it:)
