### ISSUE TITLE
Shield removes scripts without content

### ISSUE THREAD

**Issue by dsmith-digitalmint** [kindspells/astro-shield#151]
When building the application with the following script:

```
<script
    type="text/javascript" 
    id="Cookiebot"
    src="https://consent.cookiebot.com/uc.js"
    data-cbid="d14922fe-e985-4886-9910-cf8a45c1406b"
    data-blockingmode="auto"
    async>
</script>
```

I get the following error:
`09:15:11 [WARN] [@kindspells/astro-shield-post-config-setup] Script "https://consent.cookiebot.com/uc.js" must have either a src/href attribute or content, but not both. Removing it.`

**Comment by castarco** [comment]
Hi @dsmith-digitalmint , I'm sorry for my delay in responding to this issue. These past weeks I've been overloaded.

You can avoid this issue by removing all spaces inside the `<script>` block. So, instead of writing:
```html
<script
    type="text/javascript" 
    id="Cookiebot"
    src="https://consent.cookiebot.com/uc.js"
    data-cbid="d14922fe-e985-4886-9910-cf8a45c1406b"
    data-blockingmode="auto"
    async>
</script>
```

Write:
```html
<script
    type="text/javascript" 
    id="Cookiebot"
    src="https://consent.cookiebot.com/uc.js"
    data-cbid="d14922fe-e985-4886-9910-cf8a45c1406b"
    data-blockingmode="auto"
    async></script>
```

I'll be working on a more flexible solution, but this will solve your problem for now.

**Comment by smithcoin** [comment]
I tried that and got the following error:

<img width="1075" alt="Screenshot 2024-11-06 at 4 22 55 PM" src="https://github.com/user-attachments/assets/08a6b727-50bb-43ce-9268-6c15f70530ba">

DId you want to put another bounty on this issue like we discussed?
