### ISSUE TITLE
Support CSP headers generation for static content on Netlify

### ISSUE THREAD

**Issue by castarco** [kindspells/astro-shield#65]
To improve the usability of Astro-Shield, it would be good to support the generation of headers metadata specific for the Netlify provider, so we can generate CSP headers for static content.

## Reference
- See https://docs.netlify.com/routing/headers/

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kindspells) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kindspells/astro-shield/issues/65">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kindspells/astro-shield/issues/65/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kindspells/astro-shield/issues/65/pledge.svg">
</picture>
</a>

**Comment by dsmith-digitalmint** [comment]
Is there the ability to configure the path of the _headers file? Here is my current setup:

`public/headers`:
```

**Comment by castarco** [comment]
Hi @dsmith-digitalmint , it works like this:

1. You can have a `_headers` file in your `public/` directory, where you specify some headers. This is optional. But in case you do, the syntax is the one specified in https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file , it would be something like...
   ```
   # a path:
   /templates/index.html
     # headers for that path:
     X-Frame-Options: DENY
     X-XSS-Protection: 1; mode=block
   # another path:
   /templates/index2.html
     # headers for that path:
     X-Frame-Options: SAMEORIGIN
   ```
2. When you run `astro build`, if Astro-Shield is configured as stated in the documentation ( https://astro-shield.kindspells.dev/guides/hosting-integrations/netlify/ ), it will either:
   - "patch" the `_headers` file after it is copied from `public/` to `dist/`
   - or create a new one in case you opted for not having a `_headers` file in your `public/` directory.

From my tests, Netlify takes care of running `astro build` for us and reading the patched/generated `_headers` file, without requiring from us any extra step such as committing the patched/generated file.

There is one strange detail, though, that is a bit confusing to me (I'm not even sure if the behavior is correct or not, as I didn't had time to check it thoroughly):
- When I load a page for the first time, it has the `content-security-policy` header as we want. When I refresh the page... the header isn't there, but I'm not sure if that's because the page is actually not dowloaded again due to its cached nature (when I force a "real" refresh, the `content-security-policy` header is there again).

Now, I've tested this workflow for just one day and a half, so I think it is quite plausible that there might be some holes in it, or some mistakes in my understanding.

There are some things that you could check:
- Are you following a different workflow? Is there any relevant difference that we should account for?
- Do you use a different format for the entries in the `_headers` file present in your `public/` directory?
- Can you verify if the `_headers` file is properly "patched/generated" in your `dist/` directory when you run `astro build` locally?

**Comment by castarco** [comment]
P.S.: Ah, I see, it's missing some entries in the configuration object.

```js
export default defineConfig({
  site: 'my-site',
  integrations: [
      mdx(), 
      tailwind(),
      icon(),
      sitemap(),
      shield({
        securityHeaders: {
          enableOnStaticPages: { provider: "netlify" },
          contentSecurityPolicy: {},
        }
      }),
  ],
});
```
